server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/subhm4dev/ecom-config-repo.git}
          default-label: main
          clone-on-start: true
          force-pull: true
          search-paths: '{application}'
          # Authentication for private repository
          username: ${GITHUB_USERNAME:subhm4dev}
          password: ${GITHUB_TOKEN:}
          # Alternative: Use SSH URL instead
          # uri: ${CONFIG_REPO_URI:git@github.com:subhm4dev/ecom-config-repo.git}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

logging:
  level:
    org.springframework.cloud.config: INFO

